In [1]:
import pandas as pd 
import numpy as np

In [2]:
raw_sessiondata = pd.read_csv("20210113-133853.csv", skiprows=6, delimiter = ';')

In [3]:
#Add a column for 'timestamps'
import time
import datetime
import ciso8601

timestamp = []
for i in range(len(raw_sessiondata.index)):
    t = raw_sessiondata['PC-TIME'].iloc[i]
    ts= ciso8601.parse_datetime(t)
    if i == 0:
        t0= time.mktime(ts.timetuple())+ts.microsecond/1000000
        timestamp.append(np.around(t0-t0,3))
    else:
        tnow = time.mktime(ts.timetuple())+ts.microsecond/1000000
        timestamp.append(np.around(tnow-t0,3))

raw_sessiondata['timestamps'] = timestamp

In [11]:
df_group_msg = raw_sessiondata.groupby('MSG')

## Reward Delivery Timestamp

In [13]:
# Get lick onsets 
df_openvalve = df_group_msg.get_group('open_valve')
timestamps_reward = df_openvalve.timestamps.to_numpy()

In [14]:
timestamps_reward

array([  21.663,   21.713,   62.417,   62.468,   83.212,   83.262,
        113.982,  114.032,  134.949,  135.   ,  165.786,  165.837,
        196.663,  196.713,  227.561,  227.61 ,  248.356,  248.406,
        279.167,  279.217,  319.908,  319.959,  360.618,  360.668,
        391.357,  391.408,  412.06 ,  412.111,  452.792,  452.842,
        483.492,  483.541,  514.201,  514.252,  534.962,  535.012,
        565.695,  565.745,  586.461,  586.511,  617.158,  617.209,
        657.912,  657.962,  688.767,  688.817,  729.607,  729.657,
        750.312,  750.362,  771.044,  771.094,  811.816,  811.865,
        852.521,  852.571,  873.256,  873.306,  913.982,  914.033,
        954.7  ,  954.751,  995.414,  995.464, 1016.162, 1016.212,
       1056.911, 1056.962, 1077.596, 1077.647, 1118.352, 1118.403,
       1139.08 , 1139.13 , 1159.774, 1159.824, 1200.524, 1200.575,
       1221.257, 1221.307, 1251.99 , 1252.041, 1282.766, 1282.817,
       1303.48 , 1303.531, 1324.199, 1324.249, 1354.96 , 1355.

In [38]:
evenindex = np.arange(0, len(timestamps_reward) + 2, 2)

### Timestamps where Reward is ON

In [41]:
rewardON = np.take(timestamps_reward, evenindex[:-1])
rewardON 

array([  21.663,   62.417,   83.212,  113.982,  134.949,  165.786,
        196.663,  227.561,  248.356,  279.167,  319.908,  360.618,
        391.357,  412.06 ,  452.792,  483.492,  514.201,  534.962,
        565.695,  586.461,  617.158,  657.912,  688.767,  729.607,
        750.312,  771.044,  811.816,  852.521,  873.256,  913.982,
        954.7  ,  995.414, 1016.162, 1056.911, 1077.596, 1118.352,
       1139.08 , 1159.774, 1200.524, 1221.257, 1251.99 , 1282.766,
       1303.48 , 1324.199, 1354.96 , 1395.694, 1426.417, 1447.171,
       1487.902, 1518.635, 1559.434, 1590.189, 1610.949, 1631.679,
       1672.381, 1713.099, 1743.868, 1764.647, 1785.393, 1816.177,
       1846.955, 1887.692, 1928.416, 1959.162, 1979.881, 2010.612,
       2051.355, 2092.261, 2113.054, 2143.916, 2174.683, 2195.423,
       2226.153, 2267.02 , 2307.783])

### Timestamps where Reward is OFF

In [42]:
odd = evenindex-1
oddindex = odd[1:]
rewardOFF = np.take(timestamps_reward, oddindex)
rewardOFF 

array([  21.713,   62.468,   83.262,  114.032,  135.   ,  165.837,
        196.713,  227.61 ,  248.406,  279.217,  319.959,  360.668,
        391.408,  412.111,  452.842,  483.541,  514.252,  535.012,
        565.745,  586.511,  617.209,  657.962,  688.817,  729.657,
        750.362,  771.094,  811.865,  852.571,  873.306,  914.033,
        954.751,  995.464, 1016.212, 1056.962, 1077.647, 1118.403,
       1139.13 , 1159.824, 1200.575, 1221.307, 1252.041, 1282.817,
       1303.531, 1324.249, 1355.01 , 1395.745, 1426.467, 1447.222,
       1487.952, 1518.685, 1559.483, 1590.238, 1610.999, 1631.73 ,
       1672.431, 1713.15 , 1743.919, 1764.698, 1785.443, 1816.227,
       1847.005, 1887.743, 1928.466, 1959.212, 1979.931, 2010.662,
       2051.406, 2092.311, 2113.105, 2143.967, 2174.733, 2195.473,
       2226.204, 2267.07 , 2307.833])

### Calculating the Difference between Reward ON - OFF -- Reward Duration

In [44]:
reward_duration = rewardOFF - rewardON
reward_duration

array([0.05 , 0.051, 0.05 , 0.05 , 0.051, 0.051, 0.05 , 0.049, 0.05 ,
       0.05 , 0.051, 0.05 , 0.051, 0.051, 0.05 , 0.049, 0.051, 0.05 ,
       0.05 , 0.05 , 0.051, 0.05 , 0.05 , 0.05 , 0.05 , 0.05 , 0.049,
       0.05 , 0.05 , 0.051, 0.051, 0.05 , 0.05 , 0.051, 0.051, 0.051,
       0.05 , 0.05 , 0.051, 0.05 , 0.051, 0.051, 0.051, 0.05 , 0.05 ,
       0.051, 0.05 , 0.051, 0.05 , 0.05 , 0.049, 0.049, 0.05 , 0.051,
       0.05 , 0.051, 0.051, 0.051, 0.05 , 0.05 , 0.05 , 0.051, 0.05 ,
       0.05 , 0.05 , 0.05 , 0.051, 0.05 , 0.051, 0.051, 0.05 , 0.05 ,
       0.051, 0.05 , 0.05 ])

## Creating DataFrame: 'session.reward'

In [45]:
# intialise data of lists. 
data = {'timestamps':rewardON,
       'duration': reward_duration} 
# Create DataFrame 
df_reward = pd.DataFrame(data)

In [46]:
df_reward

timestamps  duration
0       21.663     0.050
1       62.417     0.051
2       83.212     0.050
3      113.982     0.050
4      134.949     0.051
..         ...       ...
70    2174.683     0.050
71    2195.423     0.050
72    2226.153     0.051
73    2267.020     0.050
74    2307.783     0.050

[75 rows x 2 columns]